# Generated by Django 4.0.4 on 2022-08-02 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
