# Generated by Django 4.0.4 on 2022-05-15 05:55

import django.contrib.postgres.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=500)),
                ('composition', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), size=5)),
                ('expiration', models.IntegerField()),
                ('cost', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
