# Generated by Django 4.0.4 on 2022-05-15 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='searchable',
            field=models.BooleanField(default=True),
        ),
    ]
