# Generated by Django 4.0.4 on 2022-08-02 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0002_medicine_searchable'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='min_quantity',
            field=models.IntegerField(default=100),
        ),
    ]
