# Generated by Django 4.0.4 on 2022-05-15 05:55

import datetime
import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
import django.contrib.postgres.fields.hstore
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=15, unique=True)),
                ('password', models.CharField(max_length=88)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=30, null=True)),
                ('user_phone', models.CharField(max_length=15, null=True)),
                ('user_email', models.EmailField(max_length=254, null=True)),
                ('employee_name', models.CharField(max_length=30, null=True)),
                ('employee_phone', models.CharField(max_length=15, null=True)),
                ('items', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.hstore.HStoreField(), size=20)),
                ('coords', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('order_date', models.DateField(default=datetime.date(2022, 5, 15))),
                ('address', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('P', 'Pending'), ('C', 'Completed')], default='P', max_length=1)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.employee')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
